import { makeStyles } from 'tss-react/mui';

const useHomeStyles = (isMobile: boolean) => {
  return makeStyles<{ isMobile: boolean }>()((theme, { isMobile }) => ({
    aboutUsRoot: {
      width: '100%',
      background: '#fff',
      boxShadow: '0 0 0 2px #e0e7ef',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: isMobile ? 2 : 4,
      minHeight: 380,
      paddingTop: isMobile ? theme.spacing(6) : 0,
      flexDirection: isMobile ? 'column' : 'row',
    },
    aboutUsLeft: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: isMobile ? 'center' : 'flex-start',
      height: '100%',
      padding: isMobile ? theme.spacing(1.5) : theme.spacing(4),
    },
    aboutUsTitleWrap: {
      width: '100%',
      display: 'flex',
      flexDirection: 'row',
      gap: isMobile ? theme.spacing(1.5) : theme.spacing(3),
      marginBottom: isMobile ? theme.spacing(2) : theme.spacing(3),
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    aboutUsTitle1: {
      paddingLeft: isMobile ? theme.spacing(2) : theme.spacing(6),
      paddingRight: isMobile ? theme.spacing(2) : theme.spacing(6),
      paddingTop: isMobile ? theme.spacing(1) : theme.spacing(1.5),
      paddingBottom: isMobile ? theme.spacing(1) : theme.spacing(1.5),
      borderRadius: 999,
      background: 'linear-gradient(180deg, #0A4FA4 0%, #041E3E 100%)',
      color: '#fff',
      fontWeight: 700,
      fontSize: isMobile ? 16 : 40,
      boxShadow: '0 2px 8px 0 #0A4FA422',
      border: '2px solid #0A4FA4',
      transition: 'all 0.2s',
      textAlign: 'center',
      minWidth: isMobile ? 90 : 'unset',
    },
    aboutUsTitle2: {
      paddingLeft: isMobile ? theme.spacing(2) : theme.spacing(6),
      paddingRight: isMobile ? theme.spacing(2) : theme.spacing(6),
      paddingTop: isMobile ? theme.spacing(1) : theme.spacing(1.5),
      paddingBottom: isMobile ? theme.spacing(1) : theme.spacing(1.5),
      borderRadius: 999,
      background: '#fff',
      color: '#0A4FA4',
      fontWeight: 700,
      fontSize: isMobile ? 16 : 40,
      border: '2px solid #e0e7ef',
      boxShadow: '0 2px 10px 0 #0463EE66',
      transition: 'all 0.2s',
      textAlign: 'center',
      minWidth: isMobile ? 90 : 'unset',
    },
    aboutUsDesc: {
      color: theme.palette.primary.dark,
      padding: isMobile ? theme.spacing(0.5) : theme.spacing(2),
      letterSpacing: '0.5px',
      fontSize: isMobile ? 15 : 20,
      marginBottom: isMobile ? theme.spacing(1.5) : theme.spacing(2),
      maxWidth: isMobile ? '98%' : '90%',
      lineHeight: 1.6,
      fontWeight: 400,
      paddingLeft: isMobile ? theme.spacing(2) : 0,
      paddingRight: isMobile ? theme.spacing(2) : 0,
    },
    aboutUsBtn: {
      color: theme.palette.primary.main,
      marginLeft: isMobile ? theme.spacing(2) : 0,
      marginRight: isMobile ? theme.spacing(2) : 0,
      borderColor: '#0A4FA4',
      fontWeight: 400,
      paddingLeft: theme.spacing(4),
      paddingRight: theme.spacing(4),
      paddingTop: theme.spacing(1),
      paddingBottom: theme.spacing(1),
      fontSize: isMobile ? 10 : 14,
      borderRadius: 999,
      width: 'fit-content',
      alignSelf: 'flex-start',
      marginTop: isMobile ? theme.spacing(1) : 0,
      '&:hover': {
        borderColor: '#0A4FA4',
        background: '#eaf2fb',
      },
    },
    aboutUsRight: {
      flex: 1,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
    },
    aboutUsImg: {
      width: '100%',
      borderRadius: 5,
      objectFit: 'cover',
      marginTop: isMobile ? theme.spacing(2) : 0,
      maxWidth: isMobile ? 340 : 540,
    },
    aboutUsVideoWrap: {
      flex: 1,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      height: '100%',
      position: 'relative',
      overflow: 'visible',
    },
    aboutUsVideo: {
      width: '100%',
      height: '100vh',
      objectFit: 'cover',
      top: 0,
      left: 0,
      minWidth: '100%',
      minHeight: '100%',
    },
    contactRoot: {
      width: '100%',
      paddingTop: theme.spacing(6),
      paddingBottom: theme.spacing(6),
      background: '#fff',
    },
    contactMain: {
      display: 'flex',
      width: '100%',
      flexDirection: 'column',
      alignItems: 'center',
      marginTop: theme.spacing(6),
    },
    contactImgWrap: {
      width: '95%',
      height: 300,
      display: 'flex',
      justifyContent: 'center',
      marginBottom: theme.spacing(2),
    },
    contactImg: {
      width: '100%',
      objectFit: 'cover',
    },
    contactFormWrap: {
      width: '80%',
      marginTop: isMobile ? theme.spacing(4) : 0,
      maxWidth: 420,
      borderRadius: 12,
      boxShadow: '0 4px 16px 0 #0A4FA422',
      background: 'linear-gradient(180deg, #0A4FA4 0%, #041E3E 100%)',
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(3),
      alignItems: 'center',
      padding: theme.spacing(4),
    },
    contactFieldWrap: {
      width: '100%',
    },
    contactLabel: {
      color: '#fff',
      fontWeight: 500,
      marginBottom: theme.spacing(1),
    },
    contactTextField: {
      background: '#fff',
      borderRadius: theme.shape.borderRadius,
      '& input': {
        color: '#222',
      },
      '& textarea': {
        color: '#222',
      },
    },
    contactButton: {
      marginTop: theme.spacing(2),
      background: '#fff',
      color: '#0A4FA4',
      fontWeight: 600,
      borderRadius: 999,
      paddingLeft: theme.spacing(5),
      paddingRight: theme.spacing(5),
      paddingTop: theme.spacing(1),
      paddingBottom: theme.spacing(1),
      boxShadow: 'none',
      textTransform: 'none',
      '&:hover': {
        background: '#eaf2fb',
      },
    },
    heroRoot: {
      minHeight: isMobile ? '40vh' : '100vh',
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      background: 'radial-gradient(circle at 60% 40%, #1758B4 0%, #0A264E 100%)',
      overflow: 'hidden',
    },
    heroLeftArrowBox: {
      position: 'absolute',
      left: 0,
      top: '50%',
      transform: 'translate(-50%, -50%)',
      zIndex: 2,
    },
    heroArrowBtn: {
      width: isMobile ? 40 : 150,
      height: isMobile ? 40 : 150,
      borderRadius: '50%',
      border: '3px solid #FFFFFF7D',
      background: 'transparent',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'end',
      boxShadow: 'none',
      padding: 0,
      margin: 0,
      '&:hover': {
        background: 'rgba(4,99,238,0.08)',
        boxShadow: 'none',
      },
    },
    heroMain: {
      width: '100%',
      maxWidth: 1400,
      minHeight: isMobile ? '40vh' : '60vh',
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'transparent',
    },
    heroImgBox: {
      flex: isMobile ? '0 0 40%' : '0 0 60%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      height: '100%',
    },
    heroImg: {
      marginTop: isMobile ? 0 : 10,
      marginLeft: isMobile ? 8 : 0,
      maxHeight: '80vh',
      maxWidth: isMobile ? '120%' : '100%',
      objectFit: 'contain',
      display: 'block',
    },
    heroTextBoxWrap: {
      display: 'flex',
      justifyContent: 'flex-end',
      width: '100%',
    },
    heroTextBox: {
      flex: isMobile ? '0 0 100%' : '0 0 40%',
      display: 'flex',
      maxWidth: isMobile ? 300 : 600,
      flexDirection: 'column',
      alignItems: 'flex-start',
      justifyContent: 'center',
      height: '100%',
      paddingLeft: isMobile ? 0 : 48,
      color: '#fff',
      marginRight: isMobile ? 0 : 120,
      textAlign: 'right',
      fontFamily: 'DM Serif Display',
    },
    heroTitle: {
      fontWeight: 700,
      fontSize: isMobile ? 16 : 60,
      maxWidth: isMobile ? 210 : 430,
      lineHeight: isMobile ? '26px' : '80px',
      textShadow: '0px 4px 24px rgba(0, 0, 0, 0.18)',
      letterSpacing: isMobile ? 1 : 0,
      marginTop: 0,
      marginLeft: 24,
    },
    heroTitleBlue: {
      color: '#2B7BFF',
      minWidth: isMobile ? 0 : 430,
      textShadow: '0px 4px 24px rgba(0, 0, 0, 0.18)',
    },
    heroRemoveIcon: {
      color: 'white',
      fontSize: isMobile ? 12 : 40,
      verticalAlign: 'middle',
      marginRight: 4,
      marginLeft: 4,
    },
    heroSubtitle: {
      fontWeight: 700,
      fontSize: isMobile ? 14 : 60,
      maxWidth: isMobile ? 120 : 430,
      lineHeight: isMobile ? '20px' : '80px',
      textShadow: '0px 4px 24px rgba(0, 0, 0, 0.18)',
      letterSpacing: isMobile ? 1 : 0,
    },
    heroBlueText: {
      color: '#2B7BFF',
      minWidth: isMobile ? 0 : 430,
      textShadow: '0px 4px 24px rgba(0, 0, 0, 0.18)',
    },
    heroRightArrowBox: {
      position: 'absolute',
      right: 0,
      top: '50%',
      transform: 'translate(50%, -50%)',
      zIndex: 2,
    },
    heroArrowBtnRight: {
      width: isMobile ? 40 : 150,
      height: isMobile ? 40 : 150,
      borderRadius: '50%',
      border: '3px solid #FFFFFF7D',
      background: 'transparent',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'start',
      boxShadow: 'none',
      padding: 0,
      margin: 0,
      '&:hover': {
        background: 'rgba(4,99,238,0.08)',
        boxShadow: 'none',
      },
    },
    heroArrowBackIcon: {
      fontSize: isMobile ? 8 : 32,
      marginRight: isMobile ? 8 : 32,
      color: theme.palette.primary.main,
    },
    heroArrowForwardIcon: {
      fontSize: isMobile ? 8 : 32,
      marginLeft: isMobile ? 8 : 32,
      color: theme.palette.primary.main,
    },
    mottoCardRoot: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      width: 300,
    },
    mottoCardHeadWrap: {
      position: 'relative',
      width: 240,
      height: 70,
      marginBottom: -24,
      zIndex: 2,
    },
    mottoCardHeadImg: {
      width: '100%',
      height: '100%',
    },
    mottoCardFishText: {
      position: 'absolute',
      top: '50%',
      left: '55%',
      transform: 'translate(-50%, -50%)',
      fontWeight: 600,
      color: '#0A4FA4',
      fontSize: 20,
      whiteSpace: 'nowrap',
    },
    mottoCardBox: {
      width: 320,
      height: 300,
      background: '#fff',
      borderRadius: 4,
      boxShadow: '0 4px 24px 0 #00000022',
      position: 'relative',
      overflow: 'hidden',
      padding: 0,
      marginBottom: theme.spacing(2),
    },
    mottoCardImgWrap: {
      width: '100%',
      height: '100%',
      position: 'absolute',
      top: 0,
      left: 0,
      zIndex: 1,
    },
    mottoCardImg: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
    },
    mottoCardButtonWrap: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      width: '100%',
      zIndex: 3,
      background: 'rgba(10, 79, 164, 0.7)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      height: 48,
    },
    mottoCardButton: {
      width: '100%',
      height: '100%',
      background: 'transparent',
      color: '#fff',
      fontWeight: 600,
      fontSize: 20,
      boxShadow: 'none',
      borderRadius: 0,
      '&:hover': {
        background: 'rgba(10, 79, 164, 0.85)',
      },
    },
    mottoCardTitle: {
      textAlign: 'center',
      fontWeight: 600,
      color: '#fff',
      maxWidth: 240,
      fontSize: 22,
      lineHeight: 1.2,
    },
    newsRoot: {
      width: '100%',
      paddingTop: isMobile ? theme.spacing(2) : theme.spacing(6),
      paddingBottom: isMobile ? theme.spacing(2) : theme.spacing(6),
      background: '#fff',
      position: 'relative',
    },
    newsFishesImg: {
      position: 'absolute',
      left: 0,
      top: -10,
      zIndex: 0,
      display: isMobile ? 'none' : '',
    },
    newsScrollWrap: {
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      alignItems: 'stretch',
      marginTop: theme.spacing(6),
      gap: theme.spacing(8),
      width: '100%',
      overflowX: 'auto',
      overflowY: 'hidden',
      scrollbarWidth: 'none',
      msOverflowStyle: 'none',
      '&::-webkit-scrollbar': { display: 'none' },
    },
    newsScrollCenter: {
      justifyContent: 'center',
    },
    newsScrollFlexStart: {
      justifyContent: 'flex-start',
    },
    newsOverflowBox: {
      marginLeft: -theme.spacing(7),
    },
    newsCardOuter: {
      minWidth: 320,
      maxWidth: 380,
      width: 340,
      boxSizing: 'border-box',
      flex: '0 0 auto',
      height: '100%',
      display: 'flex',
      alignItems: 'stretch',
    },
    newsCardOuterFirst: {
      marginLeft: theme.spacing(4),
    },
    newsCardOuterLast: {
      marginRight: theme.spacing(4),
    },
    newsCardInner: {
      width: '90%',
      marginLeft: 'auto',
      marginRight: 'auto',
      height: '100%',
    },
    newsCardRoot: {
      width: 370,
      height: 480,
      overflow: 'hidden',
      boxShadow: '0 2px 12px 0 #e0e7ef',
      background: '#fff',
      display: 'flex',
      flexDirection: 'column',
      borderRadius: 3,
      position: 'relative',
    },
    newsCardImgWrap: {
      position: 'relative',
      height: 400,
      width: '100%',
    },
    newsCardImg: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      objectPosition: 'center',
    },
    newsCardDateBox: {
      position: 'absolute',
      top: 12,
      left: 12,
      background: '#E0E2E3C2',
      paddingLeft: theme.spacing(1),
      paddingRight: theme.spacing(1),
      paddingTop: theme.spacing(0.5),
      paddingBottom: theme.spacing(0.5),
      boxShadow: theme.shadows[1],
      textAlign: 'center',
    },
    newsCardDateDay: {
      fontWeight: 700,
      fontSize: 18,
      color: '#1976d2',
      lineHeight: 1,
    },
    newsCardDateMonth: {
      fontSize: 14,
      fontWeight: 700,
      color: '#1976d2',
      lineHeight: 1,
    },
    newsCardDateYear: {
      fontSize: 15,
      fontWeight: 700,
      marginTop: theme.spacing(0.5),
      color: '#1976d2',
      lineHeight: 1,
    },
    newsCardContent: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      background: '#F7FAFC',
      borderTopRightRadius: 20,
      borderTopLeftRadius: 20,
      padding: theme.spacing(2),
    },
    newsCardTitle: {
      fontWeight: 700,
      fontSize: 22,
    },
    newsCardDesc: {
      fontSize: 14,
      paddingTop: theme.spacing(0.5),
      paddingBottom: theme.spacing(0.5),
      lineHeight: 1.25,
    },
    newsCardAuthor: {
      fontSize: 14,
    },
    newsCardAuthorLink: {
      color: '#1976d2',
      textDecoration: 'underline',
      fontWeight: 600,
    },
    newsCardAuthorSpan: {
      color: '#1976d2',
      fontWeight: 600,
    },
    newsCardFooter: {
      background: '#fff',
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
      paddingBottom: theme.spacing(2),
      display: 'flex',
      justifyContent: 'flex-start',
      borderBottomLeftRadius: 3,
      borderBottomRightRadius: 3,
    },
    newsCardButton: {
      color: '#1976d2',
      borderColor: '#1976d2',
      fontWeight: 600,
      borderRadius: 999,
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
      paddingTop: theme.spacing(0.5),
      paddingBottom: theme.spacing(0.5),
      background: '#F7FAFC',
    },
  }))({ isMobile });
};

export default useHomeStyles; 